version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Sentry
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.8
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.3.1
    - 3.3.2
  - dependency-name: FluentValidation.AspNetCore
    versions:
    - 10.0.0
    - 10.0.1
    - 10.0.2
    - 10.0.3
    - 10.0.4
    - 9.4.0
    - 9.5.0
    - 9.5.1
    - 9.5.2
    - 9.5.3
    - 9.5.4
  - dependency-name: Swashbuckle.AspNetCore
    versions:
    - 5.6.3
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.7
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: Swashbuckle.AspNetCore.Annotations
    versions:
    - 5.6.3
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.7
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: Microsoft.AspNetCore.Authentication.JwtBearer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
